# Generated by Django 5.0.1 on 2024-01-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='id',
            new_name='adharno',
        ),
    ]
