# Generated by Django 5.0.1 on 2024-01-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_id_admin_adharno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adharno',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
